### PR TITLE
Update fullDescription of steps using StepParser

### PR DESCRIPTION
**Pull request by gregorylimoratto**
Add reference to StepParser to assign fullDescription.
Need to reference the StepParser file in karma-jasmine-cucumber

### CODE REVIEW

**Comment by gregorylimoratto** [comment]
In the last commit, I forgot to use the stepparser to assign fullDescription. 
Plus an other commit to karma-jasmine-cucumber to include the file.

Thanks for the merge !

**Comment by jhoguet** [comment]
@gregorylimoratto sorry for the delay. 

We're in the process of migrating to cucumberjs and in effect abandoning this (and related) repos. 

Given you have been the primary collaborator, I can transfer the repo to you... what do you think?

**Comment by gregorylimoratto** [comment]
yes, no problems. Thanks !

2015-08-04 3:49 GMT+02:00 Jonathan Hoguet <notifications@github.com>:

**Comment by jhoguet** [comment]
You should now have access to publish to the npm. 

I am going to close this pull request and you can handle it on your fork. 

I was going to transfer the repo but having thought about it more, forking seems more appropriate. I'll add a comment to the README on this repo to point to yours. 

Please let me know if you run into any issues with NPM.

**Comment by gregorylimoratto** [comment]
Hello,

Last week I release a karma plugin based on what you have done.
My goal was to remove the mapping file between gherkin and javascript, in
order to give full control to the feature file.

This plugin allow Karma to serve feature file and transform them (with a
karma preprocessor) so you don't have to handle the specs.js file.

please have a look at : https://www.npmjs.com/package/karma-jasmine-feature,
and tell me what you think of it.

2015-08-31 0:56 GMT+02:00 Jonathan Hoguet notifications@github.com:

**Comment by jhoguet** [comment]
well done... 

did you try out cucumberjs-karma at all?

**Pull request closed without merging**
